name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need all the commits
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - uses: actions/setup-node@v2
      - name: RSpec
        run: bundle exec rspec
      - name: commitlint
        run: |
          yarn add @commitlint/{config-conventional,cli}
          yarn run commitlint --from "$(git rev-list --max-parents=0 HEAD)"
